"""
NSE Stock Universe - Comprehensive list of all NSE-traded stocks
Organized by indices: Nifty 50, Nifty Next 50, Nifty Midcap 150, Nifty Smallcap 250
"""

# Nifty 50 stocks
NIFTY_50 = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "ITC.NS", "SBIN.NS", "BHARTIARTL.NS", "KOTAKBANK.NS",
    "LT.NS", "AXISBANK.NS", "BAJFINANCE.NS", "ASIANPAINT.NS", "MARUTI.NS",
    "HCLTECH.NS", "TITAN.NS", "SUNPHARMA.NS", "ULTRACEMCO.NS", "NESTLEIND.NS",
    "TATAMOTORS.NS", "WIPRO.NS", "M&M.NS", "NTPC.NS", "POWERGRID.NS",
    "ONGC.NS", "TECHM.NS", "COALINDIA.NS", "TATASTEEL.NS", "ADANIENT.NS",
    "BAJAJFINSV.NS", "DIVISLAB.NS", "INDUSINDBK.NS", "DRREDDY.NS", "APOLLOHOSP.NS",
    "CIPLA.NS", "EICHERMOT.NS", "GRASIM.NS", "HINDALCO.NS", "JSWSTEEL.NS",
    "TATACONSUM.NS", "ADANIPORTS.NS", "HEROMOTOCO.NS", "BRITANNIA.NS", "SBILIFE.NS",
    "LTIM.NS", "BPCL.NS", "BAJAJ-AUTO.NS", "HDFCLIFE.NS", "SHRIRAMFIN.NS"
]

# Nifty Next 50 stocks
NIFTY_NEXT_50 = [
    "ADANIGREEN.NS", "ADANIPOWER.NS", "AMBUJACEM.NS", "ATGL.NS", "BANKBARODA.NS",
    "BERGEPAINT.NS", "BEL.NS", "BOSCHLTD.NS", "CANBK.NS", "CHOLAFIN.NS",
    "COLPAL.NS", "DLF.NS", "DABUR.NS", "GAIL.NS", "GODREJCP.NS",
    "HAVELLS.NS", "HDFCAMC.NS", "ICICIPRULI.NS", "INDIGO.NS", "IOC.NS",
    "JINDALSTEL.NS", "LICHSGFIN.NS", "LUPIN.NS", "MARICO.NS", "MCDOWELL-N.NS",
    "MUTHOOTFIN.NS", "NAUKRI.NS", "NMDC.NS", "PAGEIND.NS", "PETRONET.NS",
    "PIDILITIND.NS", "PNB.NS", "SIEMENS.NS", "SBICARD.NS", "SHREECEM.NS",
    "TATAPOWER.NS", "TORNTPHARM.NS", "TRENT.NS", "UNIONBANK.NS", "UPL.NS",
    "VEDL.NS", "VOLTAS.NS", "ZOMATO.NS", "BANDHANBNK.NS", "HAL.NS",
    "TVSMOTOR.NS", "GLAND.NS", "PERSISTENT.NS", "DMART.NS", "TATACOMM.NS"
]

# Nifty Midcap 150 (subset - top 100)
NIFTY_MIDCAP_150 = [
    "AARTIIND.NS", "ABB.NS", "ACC.NS", "AIAENG.NS", "ALKEM.NS",
    "AMARAJABAT.NS", "ASTRAL.NS", "ATUL.NS", "AUROPHARMA.NS", "BALKRISIND.NS",
    "BATAINDIA.NS", "BHARATFORG.NS", "BHEL.NS", "BIOCON.NS", "BOSCHLTD.NS",
    "CUB.NS", "CANBK.NS", "CANFINHOME.NS", "CASTROLIND.NS", "CESC.NS",
    "CHAMBLFERT.NS", "CHOLAFIN.NS", "COFORGE.NS", "CONCOR.NS", "COROMANDEL.NS",
    "CROMPTON.NS", "CUMMINSIND.NS", "DEEPAKNTR.NS", "DELTACORP.NS", "DIXON.NS",
    "ESCORTS.NS", "EXIDEIND.NS", "FEDERALBNK.NS", "GMRINFRA.NS", "GNFC.NS",
    "GODFRYPHLP.NS", "GODREJIND.NS", "GODREJPROP.NS", "GRANULES.NS", "GUJGASLTD.NS",
    "HAPPSTMNDS.NS", "HEXAWARE.NS", "HINDPETRO.NS", "IBREALEST.NS", "IDFCFIRSTB.NS",
    "IEX.NS", "IGL.NS", "INDHOTEL.NS", "INDUSTOWER.NS", "IRB.NS",
    "IRCTC.NS", "IRFC.NS", "JUBLFOOD.NS", "KANSAINER.NS", "KEI.NS",
    "LALPATHLAB.NS", "LAURUSLABS.NS", "LICHSGFIN.NS", "LTTS.NS", "MANAPPURAM.NS",
    "MAZDOCK.NS", "MFSL.NS", "MGL.NS", "MOTHERSON.NS", "MPHASIS.NS",
    "MRF.NS", "MUTHOOTFIN.NS", "NAM-INDIA.NS", "NATIONALUM.NS", "NAUKRI.NS",
    "NAVINFLUOR.NS", "NLCINDIA.NS", "OBEROIRLTY.NS", "OFSS.NS", "OIL.NS",
    "PAYTM.NS", "PEL.NS", "PERSISTENT.NS", "PIIND.NS", "POLICYBZR.NS",
    "POLYCAB.NS", "PVR.NS", "RECLTD.NS", "SAIL.NS", "SBICARD.NS",
    "SCHAEFFLER.NS", "SFL.NS", "SJVN.NS", "SONACOMS.NS", "SRTRANSFIN.NS",
    "SUNDARMFIN.NS", "SUNDRMFAST.NS", "SUNTV.NS", "SYNGENE.NS", "TATACHEM.NS",
    "TATAELXSI.NS", "TATATECH.NS", "TEAMLEASE.NS", "THERMAX.NS", "TIMKEN.NS",
    "TORNTPOWER.NS", "TTKPRESTIG.NS", "TUBEINVEST.NS", "UBL.NS", "UNITDSPR.NS"
]

# Nifty Smallcap 250 (subset - top 50)
NIFTY_SMALLCAP_250 = [
    "ANANDRATHI.NS", "ANURAS.NS", "APLAPOLLO.NS", "ASAHIINDIA.NS", "ASHOKLEY.NS",
    "AVADHSUGAR.NS", "BAJAJHLDNG.NS", "BASF.NS", "BLUEDART.NS", "BLUESTARCO.NS",
    "BRIGADE.NS", "CAPLIPOINT.NS", "CCL.NS", "CENTURYTEX.NS", "CERA.NS",
    "CLEAN.NS", "CONCORDBIO.NS", "CUB.NS", "CYIENT.NS", "DATAPATTNS.NS",
    "DEEPAKFERT.NS", "DCMSHRIRAM.NS", "DPWIRES.NS", "ELECTCAST.NS", "ELGIEQUIP.NS",
    "EMAMILTD.NS", "FINEORG.NS", "FINPIPE.NS", "FSL.NS", "GALAXYSURF.NS",
    "GARFIBRES.NS", "GILLETTE.NS", "GLAXO.NS", "GLENMARK.NS", "GOCOLORS.NS",
    "GPIL.NS", "GRAPHITE.NS", "GREAVESCOT.NS", "GRINDWELL.NS", "GULFOILLUB.NS",
    "HEG.NS", "HEIDELBERG.NS", "HFCL.NS", "HIMATSEIDE.NS", "HINDCOPPER.NS",
    "HINDZINC.NS", "HONAUT.NS", "HSIL.NS", "HUDCO.NS", "IBREALEST.NS"
]

# Banking stocks
BANKING_STOCKS = [
    "HDFCBANK.NS", "ICICIBANK.NS", "KOTAKBANK.NS", "AXISBANK.NS", "SBIN.NS",
    "INDUSINDBK.NS", "BANKBARODA.NS", "PNB.NS", "CANBK.NS", "UNIONBANK.NS",
    "FEDERALBNK.NS", "BANDHANBNK.NS", "IDFCFIRSTB.NS", "RBLBANK.NS", "YESBANK.NS",
    "AUBANK.NS", "CHOLAFIN.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "MUTHOOTFIN.NS",
    "LICHSGFIN.NS", "SBICARD.NS", "HDFCAMC.NS", "HDFCLIFE.NS", "SBILIFE.NS"
]

# IT stocks
IT_STOCKS = [
    "TCS.NS", "INFY.NS", "WIPRO.NS", "HCLTECH.NS", "TECHM.NS",
    "LTIM.NS", "LTTS.NS", "PERSISTENT.NS", "COFORGE.NS", "MPHASIS.NS",
    "MINDTREE.NS", "OFSS.NS", "TATAELXSI.NS", "CYIENT.NS", "SONATA.NS",
    "HAPPSTMNDS.NS", "HEXAWARE.NS", "ROUTE.NS", "NAUKRI.NS", "ZOMATO.NS"
]

# Pharma stocks
PHARMA_STOCKS = [
    "SUNPHARMA.NS", "DRREDDY.NS", "DIVISLAB.NS", "CIPLA.NS", "LUPIN.NS",
    "AUROPHARMA.NS", "TORNTPHARM.NS", "BIOCON.NS", "ALKEM.NS", "LAURUSLABS.NS",
    "GLENMARK.NS", "GRANULES.NS", "SYNGENE.NS", "GLAND.NS", "LALPATHLAB.NS",
    "APOLLOHOSP.NS", "MAXHEALTH.NS", "FORTIS.NS", "METROPOLIS.NS", "THYROCARE.NS"
]

# Auto stocks
AUTO_STOCKS = [
    "MARUTI.NS", "TATAMOTORS.NS", "M&M.NS", "EICHERMOT.NS", "BAJAJ-AUTO.NS",
    "HEROMOTOCO.NS", "TVSMOTOR.NS", "ASHOKLEY.NS", "ESCORTS.NS", "MOTHERSON.NS",
    "BHARATFORG.NS", "APOLLOTYRE.NS", "MRF.NS", "BALKRISIND.NS", "EXIDEIND.NS",
    "SONACOMS.NS", "BOSCHLTD.NS", "MINDAIND.NS", "ENDURANCE.NS", "SUNDRMFAST.NS"
]

# Energy & Power stocks
ENERGY_STOCKS = [
    "RELIANCE.NS", "ONGC.NS", "BPCL.NS", "IOC.NS", "HINDPETRO.NS",
    "OIL.NS", "GAIL.NS", "PETRONET.NS", "IGL.NS", "MGL.NS",
    "NTPC.NS", "POWERGRID.NS", "TATAPOWER.NS", "ADANIGREEN.NS", "ADANIPOWER.NS",
    "COALINDIA.NS", "NMDC.NS", "VEDL.NS", "HINDZINC.NS", "HINDCOPPER.NS"
]

# FMCG stocks
FMCG_STOCKS = [
    "HINDUNILVR.NS", "ITC.NS", "NESTLEIND.NS", "BRITANNIA.NS", "DABUR.NS",
    "MARICO.NS", "GODREJCP.NS", "COLPAL.NS", "TATACONSUM.NS", "UBL.NS",
    "MCDOWELL-N.NS", "RADICO.NS", "EMAMILTD.NS", "PAGEIND.NS", "JYOTHYLAB.NS",
    "VBL.NS", "GODFRYPHLP.NS", "HONASA.NS", "ZYDUSWELL.NS", "GILLETTE.NS"
]

# Combine all stocks
ALL_NSE_STOCKS = list(set(
    NIFTY_50 + NIFTY_NEXT_50 + NIFTY_MIDCAP_150 + NIFTY_SMALLCAP_250 +
    BANKING_STOCKS + IT_STOCKS + PHARMA_STOCKS + AUTO_STOCKS + 
    ENERGY_STOCKS + FMCG_STOCKS
))

# Stock metadata
STOCK_SECTORS = {
    "Banking & Finance": BANKING_STOCKS,
    "Information Technology": IT_STOCKS,
    "Pharmaceuticals": PHARMA_STOCKS,
    "Automobile": AUTO_STOCKS,
    "Energy & Power": ENERGY_STOCKS,
    "FMCG": FMCG_STOCKS
}

def get_all_nse_stocks():
    """Get complete list of NSE stocks"""
    return sorted(ALL_NSE_STOCKS)

def get_stocks_by_sector(sector):
    """Get stocks for a specific sector"""
    return STOCK_SECTORS.get(sector, [])

def get_nifty_50():
    """Get Nifty 50 stocks"""
    return NIFTY_50

def get_nifty_100():
    """Get Nifty 100 stocks (Nifty 50 + Next 50)"""
    return NIFTY_50 + NIFTY_NEXT_50

def get_stock_count():
    """Get total count of stocks in database"""
    return len(ALL_NSE_STOCKS)

if __name__ == "__main__":
    print(f"Total NSE stocks in database: {get_stock_count()}")
    print(f"Nifty 50: {len(NIFTY_50)} stocks")
    print(f"Nifty Next 50: {len(NIFTY_NEXT_50)} stocks")
    print(f"Nifty Midcap 150 (subset): {len(NIFTY_MIDCAP_150)} stocks")
    print(f"Nifty Smallcap 250 (subset): {len(NIFTY_SMALLCAP_250)} stocks")
